# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

esf_mst_sum_vector <- function(parlist, ojlist, order, minSolved, maxSolved, minSolved_design, maxSolved_design, probs, cumulative) {
    .Call('_tmt_esf_mst_sum_vector', PACKAGE = 'tmt', parlist, ojlist, order, minSolved, maxSolved, minSolved_design, maxSolved_design, probs, cumulative)
}

esf_mst_sum_vector_s1 <- function(par, oj) {
    .Call('_tmt_esf_mst_sum_vector_s1', PACKAGE = 'tmt', par, oj)
}

esf_mst_sum_vector_s2 <- function(eps, m, rcum, eps_position, minSolved, maxSolved, minSolved_design, maxSolved_design, probs, cumulative) {
    .Call('_tmt_esf_mst_sum_vector_s2', PACKAGE = 'tmt', eps, m, rcum, eps_position, minSolved, maxSolved, minSolved_design, maxSolved_design, probs, cumulative)
}

esf_nmst_sum_matrix <- function(epsi, order = 0L) {
    .Call('_tmt_esf_nmst_sum_matrix', PACKAGE = 'tmt', epsi, order)
}

